image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
    - CI=true npm test
variables:
    PUBLIC_URL: "/spendify"
pages:
  stage: deploy
  script:
    - CI=true npm run build:prod
    - rm -rf public
    - mv build/ public/
  artifacts:
    paths:
      - public # GitLab pages serve from a 'public' directory
  only:
    - master # run on master branch